'use client'

import '../globals.css'
import { Providers } from "@/components/auth/Providers";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Sidebar } from '@/components/admin/Sidebar';

export const metadata = {
  title: "Maxter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <div className="flex">
          <ToastContainer />
          <div className="hidden lg:flex">
            <Sidebar />
          </div>
          <div className="lg:h-full flex mx-auto w-full">{children}</div>
        </div>
        </Providers>
      </body>
    </html>
  );
}
