"use client";

import "../globals.css";
import { Providers } from "@/components/auth/Providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Sidebar } from "@/components/admin/Sidebar";
import { TbFileUpload, TbQrcode, TbUserCheck, TbUsers } from "react-icons/tb";
import { AiOutlineGroup } from "react-icons/ai";
import { Provider } from "react-redux";
import adminStore from "@/redux/admin/adminStore";

export const metadata = {
  title: "Maxter",
  description: "Generated by create next app",
};

const navigationItems = [
  {
    label: "Grupos",
    icon: <TbUsers className="sideBarIconSize" />,
    href: "/admin/groups",
  },
  {
    label: "Empresas",
    icon: <AiOutlineGroup className="sideBarIconSize" />,
    href: "/admin/agencies",
  },
  {
    label: "Subir Material",
    icon: <TbFileUpload className="sideBarIconSize" />,
    href: "/admin/upload",
  },
  {
    label: "Usuarios",
    icon: <TbUserCheck className="sideBarIconSize" />,
    href: "/admin/users",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <Providers>
          <div className="flex">
            <ToastContainer />
            <div className="hidden lg:flex">
              <Sidebar navigationItems={navigationItems} />
            </div>
            <div className="lg:h-full flex mx-auto w-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
